name: Test

on:
  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-buildtrain-${{ github.ref }}-1
  cancel-in-progress: true



jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: [ self-hosted, linux, ARM64 ]
    steps:
